apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: app

build:
  insecureRegistries:
    - registry
  artifacts:
    - image: app
  local:
    useBuildkit: true

deploy:
  helm:
    releases:
      - name: app
        chartPath: app-chart
        namespace: app
        createNamespace: true
        setValues:
          frontend.image.registry: registry.localhost:5000
          frontend.image.repository: app
        setValueTemplates:
          frontend.image.tag: "{{.IMAGE_TAG_app}}"
